### ISSUE TITLE
Media control configuration

### ISSUE THREAD

**Issue by sanihaq** [erikas-taroza/simple_audio#13]
- need a way to set media information in media control notification
- ways to disable keys (preferably only show the key needed)

p.s - see [this repository](https://github.com/sanihaq/simple_music_player) for a work in progress project using this plugin package.

**Comment by erikas-taroza** [comment]
> * need a way to set media information in media control notification

This is implemented. See [here].(https://pub.dev/documentation/simple_audio/latest/simple_audio/SimpleAudio/setMetadata.html)



> * ways to disable keys (preferably only show the key needed)

In `SimpleAudio.init()`, there is a parameter called `actions` which allows for configuration of supported actions for the OS's media controller. This can't be changed during runtime though. If that is what you need, I can add it.

**Comment by sanihaq** [comment]
@erikas-taroza I think ability to change it during runtime could be useful. But for what I need, I think `init` would do the job.
Could please you add an example in the repo. Thank you.

**Comment by erikas-taroza** [comment]
> Could you please add an example in the repo. Thank you.

Yes :)

**Comment by sanihaq** [comment]
didn't work

```dart
  SimpleAudio.init(
    actions: [
      NotificationActions.playPause,
      NotificationActions.skipNext,
    ],
  );
```

```
W/MediaSessionCompat(29924): Couldn't find a unique registered media button receiver in the given context.
D/AndroidRuntime(29924): Shutting down VM
E/AndroidRuntime(29924): FATAL EXCEPTION: main
E/AndroidRuntime(29924): Process: com.example.simple_music_player, PID: 29924
E/AndroidRuntime(29924): android.app.RemoteServiceException: Bad notification(tag=null, id=777) posted from package com.example.simple_music_player, crashing app(uid=10090, pid=29924): Couldn't inflate contentViewsjava.lang.IllegalArgumentException: setShowActionsInCompactView: action 2 out of bounds (max 1)
E/AndroidRuntime(29924): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2262)
E/AndroidRuntime(29924): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(29924): 	at android.os.Looper.loop(Looper.java:255)
E/AndroidRuntime(29924): 	at android.app.ActivityThread.main(ActivityThread.java:8212)
```

**Comment by erikas-taroza** [comment]
Were you testing on Android?

This error: `setShowActionsInCompactView: action 2 out of bounds (max 1)` is related to `androidCompactPlaybackActions` in `init()`

**Comment by sanihaq** [comment]
@erikas-taroza how would I solve it? yes it's in android. But Linux also seems to have the same problem, it's stuck at build.

**Comment by erikas-taroza** [comment]
> @erikas-taroza how would I solve it? yes it's in android. But Linux also seems to have the same problem, it's stuck at build.

Set `androidCompactPlaybackActions` to `[0, 1`]. The indices in this array correspond to the indices in `actions`. However, this shouldn't affect Linux. Let me test with 2 actions.
