### ISSUE TITLE
Setting volume right after creating player instance, giving error.

### ISSUE THREAD

**Issue by sanihaq** [erikas-taroza/simple_audio#15]
After creating a player, changing default volume.
```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: LateInitializationError: Field '_player@384384061' has not been initialized.
#0      _player (package:simple_audio/src/simple_audio.dart)
#1      SimpleAudio.setVolume (package:simple_audio/src/simple_audio.dart:314:22)
#2      PlaybackController.setVolume (package:simple_music_player/states/player_controller.dart:72:19)
#3      _VolumeControlState.initState.<anonymous closure> (package:simple_music_player/components/volume_control.dart:27:26)
<asynchronous suspension>
```

**Comment by erikas-taroza** [comment]
Takes some time for the player to be created in `init()`. Does awaiting `init()` in `main` fix this issue?

I will update the example if it does.

**Comment by sanihaq** [comment]
@erikas-taroza yes, using `await` fix the problem. It was not giving this error before. Only happened after updating dependencies.

**Comment by erikas-taroza** [comment]
> @erikas-taroza yes, using `await` fix the problem. It was not giving this error before. Only happened after updating dependencies.

Ok I will update the example.

I appreciate you for using my plugin and helping me iron out some issues which I may have never found for a long time. I'll give you credit in the README.

**Comment by sanihaq** [comment]
@erikas-taroza thanks. You did an amazing job with this plugin. 👍

**Comment by erikas-taroza** [comment]
> @erikas-taroza thanks. You did an amazing job with this plugin. +1

Thank you for your kind words :)
