### ISSUE TITLE
Feature Request: Support playlist

### ISSUE THREAD

**Issue by Yesterday17** [erikas-taroza/simple_audio#17]
Though playlist support can be implemented outside this package, implementing it on rust side has many benefits. For example, preload and gapless playback support could be done further for better user experience.

**Comment by erikas-taroza** [comment]
Preloading and gapless playback can and should be implemented. Playlists will not be implemented. I want the user to decide how that functionality is handled. I also believe that playlists are not in the scope of the project (keep it simple, provide necessary functionality for playback). 

I'm thinking a 1 item queue. For example, when calling `open()`, you can optionally call `queue()` or similarly named method. `queue()` will prepare the given file. Once playback finishes, the "done" message is sent as usual. In the callback, you can check for a `hasQueue` variable and decide whether or not to play the queued file (ex. `playQueue()`). This will be useful in case the queued file is no longer needed to play (ex. user removes that song from the app's playlist). Maybe a remove from queue method may be helpful as well. 

Let me know what you think of this idea. I am willing to compromise and make something that works for the both of us.

**Comment by Yesterday17** [comment]
I'm thinking of something like the following code explains. Note that no boundary check was added for simplicy.

```dart
final playlist = ['/tmp/1.mp3', '/tmp/2.mp3', '/tmp/3.mp3', '/tmp/4.mp4'];
int currentIndex = 0;

player.open(playlist[currentIndex], queue: playlist[currentIndex + 1]);

player.playbackStateStream.listen((event) {
    if (event == PlaybackState.Done) {
        currentIndex++;
        player.queue(playlist[currentIndex + 1]);
    }
});

// if the user has changed the playlist
player.queue(null);
// or if we do not like null
player.clearQueue();
```

**Comment by erikas-taroza** [comment]
> I'm thinking of something like the following code explains. Note that no boundary check or async/await was added to keep it straightforward.
> 
> ```dart
> final playlist = ['/tmp/1.mp3', '/tmp/2.mp3', '/tmp/3.mp3', '/tmp/4.mp4'];
> int currentIndex = 0;
> 
> player.open(playlist[currentIndex], queue: playlist[currentIndex + 1]);
> 
> player.playbackStateStream.listen((event) {
>     if (event == PlaybackState.Done) {
>         currentIndex++;
>         player.queue(playlist[currentIndex + 1]);
>     }
> });
> 
> // if the user has changed the playlist
> player.queue(null);
> // or if we do not like null
> player.clearQueue();
> ```

This looks good :). However, I think:
- `open()` should not do anything with queuing
- `clearQueue()` is the way to go

**Comment by Yesterday17** [comment]
Maybe we should also add a new state in `PlaybackState`? If there's no new state to indicate that the player has `done+play`, we may encounter such condition:

UI Elements map:
- `PlaybackState.Play`: ⏸️
- `PlaybackState.Pause`: ▶️
- `PlaybackState.Done`: ▶️ (?)

Events received when audio in the queue was used:
- `PlaybackState.Play`: At the time the previous track was played.
- `PlaybackState.Done`: At the time the previous track has finished.
- `PlaybackState.Play`: At the time when current track starts playing.

which results in: ⏸️ -> ▶️ -> ⏸️ updates in a short period of time.

**Comment by erikas-taroza** [comment]
> Maybe we should also add a new state in `PlaybackState`? If there's no new state to indicate that the player has `done+play`, we may encounter such condition:
> 
> UI Elements map:
> 
> * `PlaybackState.Play`: pause_button
> * `PlaybackState.Pause`: arrow_forward
> * `PlaybackState.Done`: arrow_forward (?)
> 
> Events received when audio in the queue was used:
> 
> * `PlaybackState.Play`: At the time the previous track was played.
> * `PlaybackState.Done`: At the time the previous track has finished.
> * `PlaybackState.Play`: At the time when current track starts playing.
> 
> which results in: pause_button -> arrow_forward -> pause_button updates in a short period of time.

I can see how this will be an issue. You will be able to see a flicker of play/pause. This wouldn't make sense for gapless playback.

I think that this is something the user can handle themselves. For example:

```dart
player.playbackStateStream.listen((event) {
    if(event == PlaybackState.done) {
        // The preloaded item can be played in a gapless manner.
        if(player.hasQueue && queuedItemValid) {
            // Display pause button.
            player.playQueue();
            return;
        }

        // Display play button.
    }

    // Handle play/pause states.
});
```

This is the expected result:

**No queue**
⏸️ -> (callback) -> (no queue) -> ▶️ -> (load your file) -> ⏸️

**Valid queue**
⏸️ -> (callback) -> (valid queue) -> ⏸️ -> ⏸️

NOTE: The first icon indicates the UI state before `done`. The second icon indicates the state when receiving `done`. The third icon represents the state when playing (after playing a new or queued item).

I don't think a state would fix this problem. We have to take into account that the preloaded item may not want to be played. Because of this, we can't send a special `playingQueue` state because `simple_audio` will never play the preloaded item by itself.

I will keep this in mind in case it is needed when I develop this functionality. Thanks for the suggestion :)

I am going to bed so I will not reply for some time.

**Comment by erikas-taroza** [comment]
Hello.

I have the core functionality complete. However, there is a crucial issue where the playback stutters when queuing something. It will take some time to fix because the issue might be from a dependency. The PR above contains the gapless playback support if you want to monitor status.

**Comment by Yesterday17** [comment]
I'm not quite familiar with audio playback and decoding. In my mind, `gapless` means that the decoder has pre-decoded some samples of the next track, and only need to pass the buffer to player right after the buffer of the previous track. It might be quick enough to receive a value from the confirmation callback, but it seems not fully `gapless`?

Or maybe human just can not distinguish the difference? :thinking:

**Comment by erikas-taroza** [comment]
> I'm not quite familiar with audio playback and decoding. In my mind, `gapless` means that the decoder has pre-decoded some samples of the next track, and only need to pass the buffer to player right after the buffer of the previous track. It might be quick enough to receive a value from the confirmation callback, but it seems not fully `gapless`?
> 
> Or maybe human just can not distinguish the difference? thinking

I'm not familiar either :). But this makes sense. Currently, the decoded sample buffer isnt actually passed anywhere. It gets decoded again. To increase the effectiveness, this should be used as you stated.

At the moment, I am trying to figure out the issue I mentioned above. For some reason, the work done in another thread somehow affects the playback in the thread for decoding :thinking:. When this is solved, I will make sure that the decoding work done in the separate thread is reused.
