### ISSUE TITLE
Content-Length error

### ISSUE THREAD

**Issue by Mark0o33** [erikas-taroza/simple_audio#31]
When I try to open audio files through HTTP it gives me this error,
Could not get "Content-Length" header for HTTP stream,
I know this is more of an issue on my side but packages like audioplayers and just_audio didn't give me this exception. Maybe if that parameter in header is null you can get length from the file instead?

**Comment by erikas-taroza** [comment]
Are you able to provide the link to the file?

The header is used for streaming the file. It gets the length of the file, but it looks like the server does not provide the header in response to a HEAD request. One way to solve this would be to read the whole file, but then that defeats the purpose of streaming.

I am currently testing without fetching the file length. It seems to be working for beginning to end playback, which is a good start. Going to see if I can get it to work with seeking as well. This would be the ideal solution.

**Comment by Mark0o33** [comment]
I can provide a link as an example, these links can expire and are generated with [Piped](https://github.com/TeamPiped/Piped).
[Example url](https://watchproxy-nl.whatever.social/videoplayback?expire=1686438078&ei=XqyEZI2eNMufgQezgL-YDw&ip=146.19.215.24&id=o-AHZtQ_kboDwRSMaK66cGbMEQ1og2QCpW0Njb0T-P2xil&itag=139&source=youtube&requiressl=yes&mh=Lu&mm=31%2C26&mn=sn-4g5lzne6%2Csn-5hne6nzd&ms=au%2Conr&mv=m&mvi=1&pl=24&gcr=de&initcwndbps=7307500&spc=qEK7BzFz4wWxNg33BF2wQpjhAcOAoLs&vprv=1&svpuc=1&mime=audio%2Fmp4&gir=yes&clen=1806468&dur=295.893&lmt=1628186164556631&mt=1686416026&fvip=5&keepalive=yes&fexp=24007246%2C51000011%2C51000022&c=ANDROID&txp=5532434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cgcr%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRAIge_D0amfnXNaMXuTLsUqRDSXk0IEdLlVDOk1eUokGCOMCIB5rtvKbqA0AM_njAUpoaXGsRLcQ07YKOXwK6ce8C3Qb&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgUs-1c0wwQtNFHOjFvL8QChKio5o9HZQd5DLGIqsbOcMCIEOUB6z62Fl5vtjE5jeud8o9_cieaGhWmL2G5rZBFttP&cpn=Yn357VKVNCSr9H_P&host=rr1---sn-4g5lzne6.googlevideo.com)

**Comment by erikas-taroza** [comment]
> I can provide a link as an example, these links can expire and are generated with [Piped](https://github.com/TeamPiped/Piped). [Example url](https://watchproxy-nl.whatever.social/videoplayback?expire=1686438078&ei=XqyEZI2eNMufgQezgL-YDw&ip=146.19.215.24&id=o-AHZtQ_kboDwRSMaK66cGbMEQ1og2QCpW0Njb0T-P2xil&itag=139&source=youtube&requiressl=yes&mh=Lu&mm=31%2C26&mn=sn-4g5lzne6%2Csn-5hne6nzd&ms=au%2Conr&mv=m&mvi=1&pl=24&gcr=de&initcwndbps=7307500&spc=qEK7BzFz4wWxNg33BF2wQpjhAcOAoLs&vprv=1&svpuc=1&mime=audio%2Fmp4&gir=yes&clen=1806468&dur=295.893&lmt=1628186164556631&mt=1686416026&fvip=5&keepalive=yes&fexp=24007246%2C51000011%2C51000022&c=ANDROID&txp=5532434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cgcr%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRAIge_D0amfnXNaMXuTLsUqRDSXk0IEdLlVDOk1eUokGCOMCIB5rtvKbqA0AM_njAUpoaXGsRLcQ07YKOXwK6ce8C3Qb&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgUs-1c0wwQtNFHOjFvL8QChKio5o9HZQd5DLGIqsbOcMCIEOUB6z62Fl5vtjE5jeud8o9_cieaGhWmL2G5rZBFttP&cpn=Yn357VKVNCSr9H_P&host=rr1---sn-4g5lzne6.googlevideo.com)

I see. They definitely don't provide the `Content-Length` header, even with a `GET` request. I implemented the fallback but it will take some time to download the whole file for playback. Maybe create a feature request to implement `HEAD` requests?

**Comment by Mark0o33** [comment]
It did solve the problem, thanks
