### ISSUE TITLE
Ubuntu 20.04 Build Error

### ISSUE THREAD

**Issue by cedarbob** [erikas-taroza/simple_audio#36]
I got the following error:

Building Linux application...
CMake Error at flutter/ephemeral/.plugin_symlinks/simple_audio/linux/CMakeLists.txt:51 (file):
  file does not recognize sub-command ARCHIVE_EXTRACT

Exception: Unable to generate build files

**Comment by erikas-taroza** [comment]
Hello. Thank you for the report.

The issue is caused by 81a15de. It looks like Ubuntu 20.04's cmake version is too old. I did not account for this.

I will get this fixed. In the meantime, you can use version 1.6.0

**Comment by cedarbob** [comment]
I went back to version 1.6.0 and got the following error:

CMake Error at cmake_install.cmake:155 (file):
  file INSTALL cannot find
  ".../music_player/linux/flutter/ephemeral/.plugin_symlinks/simple_audio/linux/libsimple_audio.so":
  No such file or directory.

I'm building with Intellij.  I'm not sure if this is a library issue or something I did or didn't do.

**Comment by erikas-taroza** [comment]
> 

Can you try running `flutter clean && flutter pub get` and then launching your app?

**Comment by cedarbob** [comment]
Didn't help.  Got same error.

**Comment by erikas-taroza** [comment]
Hm that's weird. It should be downloading the file when building the app (see [here](https://github.com/erikas-taroza/simple_audio/blob/ee3e50b662416161508387035206a568e44b7200/linux/CMakeLists.txt#L42C1-L50C8)).

I'm working on fixing the original issue. I'll upload it to pub.dev once I am done testing.

**Comment by erikas-taroza** [comment]
Hello.

I just upload v1.6.2 to pub.dev. Let me know if the changes fix your issue.

**Comment by cedarbob** [comment]
That worked.  Thanks!

**Comment by erikas-taroza** [comment]
Great!
