### ISSUE TITLE
Android 13 stuck on `setMetadata` if calling with `await`

### ISSUE THREAD

**Issue by realth000** [erikas-taroza/simple_audio#38]
Hello!

I found that when calling `setMetadata` with `await` keyword, app stuck here on Android 13.

The example app can reproduce this:

``` diff
diff --git a/example/lib/main.dart b/example/lib/main.dart
index 1f683c2..e519327 100644
--- a/example/lib/main.dart
+++ b/example/lib/main.dart
@@ -128,7 +129,7 @@ class _MyAppState extends State<MyApp> {
                 onPressed: () async {
                   String path = await pickFile();

-                  player.setMetadata(
+                  await player.setMetadata(
                     const Metadata(
                       title: "Title",
                       artist: "Artist",
```

Everything goes well without `await` keyword.

Is `setMetadata` should only used without `await`? 

Besides it's a async function so the linter will give warning "Missing an 'await' for the 'Future' computed by this expression", is there any way to make it sync if designed without `await`?

**Comment by erikas-taroza** [comment]
Hello. Thank you for reporting this issue!

I will look into what is causing this issue. You should be able to use `setMetadata` with await so this isn't intended.

**Comment by erikas-taroza** [comment]
I have fixed the issue in the commit above. Once CI passes, I will create a release and notify you here when it is done.

**Comment by erikas-taroza** [comment]
I have published the changes to pub.dev.

**Comment by realth000** [comment]
Thans! it works now.

**Comment by erikas-taroza** [comment]
> Thans! it works now.

Great!
