### ISSUE TITLE
Could not open HTTP stream

### ISSUE THREAD

**Issue by gitroberto64** [erikas-taroza/simple_audio#40]
I try to play https stream but function player.open raise a Exception:
  String path = "https://waw.ic.smcdn.pl/2380-1.aac";
  await player.stop();
  await player.open(path);
                
Exception has occurred.
FfiException (FfiException(RESULT_ERROR, Could not open HTTP stream at "https://waw.ic.smcdn.pl/2380-1.aac"

Caused by:
    0: error decoding response body: operation timed out
    1: operation timed out, null))

I test on Linux

**Comment by erikas-taroza** [comment]
Hello.

This file looks like a livestream which simple_audio does not support at the moment.

**Comment by erikas-taroza** [comment]
Closing for inactivty
