### ISSUE TITLE
Audio output issues on Windows 

### ISSUE THREAD

**Issue by dannyglover** [erikas-taroza/simple_audio#48]
There is an issue where changing audio outputs on windows results in no audio being played.

For instance, if you have a TV hooked up to your pc and start playback on the TV speakers and switch to your pc speakers, no audio is played.

I did a test on Linux and plugging in/out headphones resulted in audio continuing playback on the active device (which is expected). I will conduct more experiments shortly on Linux to test the same conditions as above to ensure that the situation works on Linux too.

I'm going to look into this asap too.
Thanks bud.

**Comment by snylonue** [comment]
I have encountered the issue recently on iOS too.

**Comment by snylonue** [comment]
It seems `CpalOutput` should be recreated after device changes so that its stream get recreated on current device.

**Comment by erikas-taroza** [comment]
> It seems `CpalOutput` should be recreated after device changes so that its stream get recreated on current device.

That is the current behavior. Maybe cpal doesn't send the [callback](https://github.com/erikas-taroza/simple_audio/blob/c370a8af2a6c16292e70fa7595b1c6281af13b39/rust/src/audio/cpal_output.rs#L78C25-L78C62) all the time.

**Comment by snylonue** [comment]
Is there any progress
