### ISSUE TITLE
Can it support `opus` format?

### ISSUE THREAD

**Issue by fzyzcjy** [erikas-taroza/simple_audio#5]
It is happy to see an open-sourced library using my open-sourced library (https://github.com/fzyzcjy/flutter_rust_bridge) that seems useful to my app ;)

So, I wonder whether this package supports opus format? The doc is not yet very elaborate so I have not found information about this.

In addition, I wonder whether it is possible to support audio recording as well? (For example, opus format)

**Comment by erikas-taroza** [comment]
Hello @fzyzcjy
Thank you for making FRB :)

> So, I wonder whether this package supports opus format? The doc is not yet very elaborate so I have not found information about this.

`simple_audio` decodes audio using [Symphonia](https://github.com/pdeljanov/Symphonia), a Rust crate that supports multiple codecs and formats. Unfortunately, this crate doesn't support opus yet. The owner stated that it is a long term goal (in 2021).

> In addition, I wonder whether it is possible to support audio recording as well? (For example, opus format)

I have no plans of support audio recording. This library is focused on playback. However, [cpal](https://github.com/RustAudio/cpal) does support recording, if you want to implement that yourself.

**Comment by fzyzcjy** [comment]
I see. Thanks :)

**Comment by Yesterday17** [comment]
`songbird` seems to have implemented a decoder for Symphonia on top of `audiopus` in their [`next`](https://github.com/serenity-rs/songbird/tree/next) branch, which might be helpful :eyes:

**Comment by erikas-taroza** [comment]
> `songbird` seems to have implemented a decoder for Symphonia on top of `audiopus` in their [`next`](https://github.com/serenity-rs/songbird/tree/next) branch, which might be helpful eyes

I'll take a look. Thanks for the suggestion :)

**Comment by erikas-taroza** [comment]
Reopening because of #29
