### ISSUE TITLE
using `stop()` function leads to weird behavior

### ISSUE THREAD

**Issue by sanihaq** [erikas-taroza/simple_audio#8]
I'm not sure if i'm doing something wrong or something wrong in the library. but trying to play using `open` after using `stop`, sometimes works sometime it doesn't.

```dart
// _player is a `SimpleAudio` instance

// calling only this funtion works
 Future<void> play(String path) async {
    await _player.stop(); // i've tried commenting this line, doesn't work.
    await _player.open(path);
  }

// calling this function before calling `play` doesn't work
Future<void> stop() async {
  if (playbackState.value != PlaybackState.done) {
     await _player.stop();
}
```

**Comment by erikas-taroza** [comment]
I did some testing. If you call `stop()` more than once before opening a file, then `simple_audio` will lock up. I have fixed this issue so you can call `stop()` as many times as you want.
